app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Username', validators=[Required()])
    room = StringField('Room Name', validators=[Required()])
    key = StringField('Room Key', validators=[Required()])
    submit = SubmitField('Enter Chatroom')
    initiateSession = SubmitField('Initiate Session')
    requestKey = SubmitField('Request Key')


class RequestKeyForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Username', validators=[Required()])
    room = StringField('Room Name', validators=[Required()])
    submit = SubmitField('Request Key')
    
    

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from flask import make_response
from . import main
from .forms import LoginForm, RequestKeyForm
import secrets
import sys
from Crypto.Cipher import AES
from Crypto import Random
from Crypto.Protocol.KDF import PBKDF2
import binascii
import uuid
from .serverm import ServerM
from .cryptographicHash import HashOperation
#import base64
from .KDCServer import KDCServer
from .ClientEncrytionJS import ClintJS
from base64 import b64decode

sessionKey = secrets.token_hex(32)
secret = 'bil548'

roomCounter = 5
peopleCounter = 0

allRooms = {} #dictionary of all rooms, room name - room key pairs
for i in range(roomCounter):
    roomName = 'room' + str(i)
    allRooms[roomName] = secrets.token_hex(16)
    
print( allRooms)

peoplePerRoom = {} #dictionary of all people in each room
allPeople = [] #array of all people
allSessionKeys = {} #dictionary of all session keys, person - session key pairs

@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        hashedPassword = HashOperation.hashBasedOnPassword(form.room.data)

        userName = form.name.data

        challangeFromServer = ServerM.insertUser(userName, hashedPassword)

        # Encrpyt challenge with the hash of the password
        iv = b'Sixteen byte key'
        cipher = AES.new(hashedPassword, AES.MODE_CFB, iv)
        msg = cipher.encrypt(challangeFromServer)
        status = ServerM.getEncrytedMessage(msg, userName)
        print(status)
        if status == True:
            sessionKeyTrue = uuid.uuid1()
        ################################################# SESSION KEY BURADA DEVREYE GİRİYOR#################





        session['key'] = form.key.data
        if( session['key'] != allRooms[session['room']]):
            session['error'] = 'invalid_key'
            return redirect(url_for('.error'))
        if( session['name'] not in allPeople):
            allPeople.append(session['name'])
            allSessionKeys[session['name']] = '123456'
        return render_template('chat.html', username=session['name'], room=session['room'], key=session['key'])
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
        form.key.data = session.get('key', '')
    return render_template('index.html', form=form)
    

@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    key = session.get('key', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', username=name, room=room, key=key)


@main.route('/initiateSession')
def initiateSession():
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        session['key'] = form.key.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
        form.key.data = session.get('key', '')
    return render_template('initiateSession.html', form = form)
    
    
@main.route('/requestKey', methods=['GET', 'POST'])
def requestKey():
    ##THESE VALUES ARE USED IN HTML FILES##
    name = session.get('name', '')
    room = session.get('room', '')
    key = allRooms[room]
    form = RequestKeyForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.requestKey'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('requestKey.html', form = form, key=key, room=room, username=name)
    
    
@main.route('/error')
def error():
    error = session.get('error', '')
    if error == 'invalid_key':
        return render_template('errorPage.html', note='Room key is incorrect.')
    return render_template('errorPage.html')
   

@main.route('/aes', methods=['GET', 'POST'])
def aes():
   message = None
   if request.method == 'POST':
        key = request.form['_key']
        iv = request.form['_iv']
        text = request.form['_text']
        result = decrypt(key, iv, text)
        resp = make_response(result)
        resp.headers['Content-Type'] = "application/json"
        return resp
        
@main.route('/decrypt2', methods=['GET', 'POST'])
def decrypt2():
    message = None
    if request.method == 'POST':
        data = request.form['data']
        roomkey = request.form['key']
        result = decrypt2(data, roomkey)
        resp = make_response(result)
        resp.headers['Content-Type'] = "application/json"
        return resp

@main.route('/chatRoom',methods = ['POST', 'GET'])
def result():
   if request.method == 'POST':

      print(request.form['submit_button'])

      roomId = KDCServer.getRoomIdForClient(request.form['submit_button'])

      sessionId  = uuid.uuid1().bytes
      clientEncyrpt = ClintJS.encrytRoomId(roomId,sessionId)
      serverEncyrypt = KDCServer.getRoomId(request.form['submit_button'],sessionId)
      if clientEncyrpt==serverEncyrypt:
          return render_template("insideChatRoom.html")
   return render_template("chatRoom.html")
    
def decrypt(key, iv, encrypted_text):
    aes = AES.new(key, AES.MODE_CBC, iv, segment_size=128)
    encrypted_text_bytes = binascii.a2b_hex(encrypted_text)
    decrypted_text = aes.decrypt(encrypted_text_bytes)
    return decrypted_text.decode('ascii')
    
    
def decrypt2(data, roomkey):    
    data = b64decode(data)
    byte = PBKDF2( roomkey.encode("utf-8"), "1234salt".encode("utf-8"), 48, 128)
    iv = byte[0:16]
    key = byte[16:48]
    cipher = AES.new(key, AES.MODE_CBC, iv)
    text = cipher.decrypt(data)
    text = text[:-text[-1]].decode("utf-8")
    return text
    
    

app/templates/chat.html
<html>
    <head>
        <title>Flask-SocketIO-Chat: {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/hmac-sha256.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/enc-base64.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9/mode-cfb.min.js"></script>
		<script type="text/javascript" charset="utf-8">
            var socket;
			var sessionkey = 'f4bfdeff0cb4982d04c0da2ee79e446e';
			
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
					var roomkey = "{{ key }}";
					var roomname = "{{ room }}";
					var username = "{{ username }}";
					
					/*
					https://stackoverflow.com/questions/59488728/aes-encrypt-in-cryptojs-decrypt-in-pycrypto
					*/
					//first iteration
					var salt = "1234salt";
					var iterations = 128;
					var bytes = CryptoJS.PBKDF2( roomkey, salt, { keySize: 48, iterations: iterations });
					var iv = CryptoJS.enc.Hex.parse( bytes.toString().slice(0, 32));
					var key = CryptoJS.enc.Hex.parse( bytes.toString().slice(32, 96));
					var ciphertext = CryptoJS.AES.encrypt( username, key, { iv: iv });
					temp = roomname + '|||' + ciphertext;
					
					//second iteration
					bytes = CryptoJS.PBKDF2(sessionkey, salt, { keySize: 48, iterations: iterations });
					iv = CryptoJS.enc.Hex.parse(bytes.toString().slice(0, 32));
					key = CryptoJS.enc.Hex.parse(bytes.toString().slice(32, 96));
					ciphertext = CryptoJS.AES.encrypt(temp, key, { iv: iv });
					
                    socket.emit('joined', {msg: ciphertext.toString()});
                });
				
				//new members & left members
                socket.on('status', function(data) {
					var data = data.msg;
					var roomkey = "{{ key }}";
					
					if( data.includes("left") != -1){
						var decrypted = runPyScript( sessionkey, '0000000000000000', data)
						decrypted = decrypted.substring( 0, decrypted.indexOf("=") + 2); //remove padding
						var username = decrypt(decrypted, roomkey);
						
						$('#chat').val($('#chat').val() + '<' + username + ' joined the chatroom>\n');
	                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
					}
                });
				
				//receiving messages
                socket.on('message', function(data) {
					var roomkey = "{{ key }}";
					var data = data.msg;
					
					//first iteration of decryption
					var decrypted = runPyScript( sessionkey, '0000000000000000', data)
					decrypted = decrypted.substring( 0, decrypted.indexOf("=") + 2); //remove padding
					var roomname = decrypted.substring( 0, decrypted.indexOf("|"));
					var temp = decrypted.substring( decrypted.indexOf("|") + 3);
					
					//second iteration of decryption
					var plaintext = decrypt(temp, roomkey);
					var username = plaintext.substring(0, plaintext.indexOf("|"));
					temp = plaintext.substring(plaintext.indexOf("|") + 3);
					var message = temp.substring(0, temp.indexOf("|")); // :))
					var mac = temp.substring(temp.indexOf("|") + 3);
					
					//MAC calculation
					var hash = CryptoJS.HmacSHA256( message, 'bil548'); //bil548 = secret
					var mac2 = CryptoJS.enc.Base64.stringify( hash);
					
					if( mac != mac2)
						$('#chat').val($('#chat').val() + 'Attention: MACs do not match for following message!\n');
					
					$('#chat').val($('#chat').val() + username + ': ' + message + '\n');
					$('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
				
				//sending messages
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
						var roomname = "{{ room }}";
						var username = "{{ username }}";
						var roomkey = "{{ key }}";
						
						//MAC calculation
						var hash = CryptoJS.HmacSHA256( text, 'bil548'); //bil548 = secret
						var hashInBase64 = CryptoJS.enc.Base64.stringify( hash);
						
						//if( text == "") //parsing purposes --> causes MAC inequality
						//	text = " ";
						var temp = username + "|||" + text + "|||" + hashInBase64;
						
						/*
						https://stackoverflow.com/questions/59488728/aes-encrypt-in-cryptojs-decrypt-in-pycrypto
						*/
						//first iteration
						var salt = "1234salt";
						var iterations = 128;
						var bytes = CryptoJS.PBKDF2(roomkey, salt, { keySize: 48, iterations: iterations });
						var iv = CryptoJS.enc.Hex.parse(bytes.toString().slice(0, 32));
						var key = CryptoJS.enc.Hex.parse(bytes.toString().slice(32, 96));
						var ciphertext = CryptoJS.AES.encrypt(temp, key, { iv: iv });
						temp = username + '|||' + roomname + '|||' + ciphertext;
						
						
						//second iteration
						bytes = CryptoJS.PBKDF2(sessionkey, salt, { keySize: 48, iterations: iterations });
						iv = CryptoJS.enc.Hex.parse(bytes.toString().slice(0, 32));
						key = CryptoJS.enc.Hex.parse(bytes.toString().slice(32, 96));
						ciphertext = CryptoJS.AES.encrypt(temp, key, { iv: iv });
						
						socket.emit('text', {msg: ciphertext.toString()});
                    }
                });
            });
			
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }
			
			/*
			https://stackoverflow.com/questions/32288722/call-python-function-from-js
			*/
			function runPyScript(key, iv, text){
			        var jqXHR = $.ajax({
			            type: "POST",
			            url: "/aes",
			            async: false,
			            data: { _key: key, _iv: iv, _text: text}
			        });

			        return jqXHR.responseText;
			}
			
			
			function decrypt(text, roomkey){
			        var jqXHR = $.ajax({
			            type: "POST",
			            url: "/decrypt2",
			            async: false,
			            data: { data: text, key: roomkey}
			        });

			        return jqXHR.responseText;
			}
			
        </script>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat: {{ room }}</h1>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
        <a href="#" onclick="leave_room();">Leave this room</a>
    </body>
	
</html>

app/templates/chatRoom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<form action="/chatRoom" method="post">
  <input type="submit" name="submit_button" value="ChatRoom1">
</form>

<form action="/chatRoom" method="post">
  <input type="submit" name="submit_button" value="ChatRoom2">
</form>

<form action="/chatRoom" method="post">
  <input type="submit" name="submit_button" value="ChatRoom3">
</form>

<form action="/chatRoom" method="post">
  <input type="submit" name="submit_button" value="ChatRoom4">
</form>
</body>
</html>

app/templates/errorPage.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
		
    <body>
        <h1>Error: {{ note }}</h1><br>
        <a href="#" onclick="leave_room();">Index page</a>
    </body>
	<script type="text/javascript" charset="utf-8">
        function leave_room() {
        	// go back to the login page
            window.location.href = "{{ url_for('main.index') }}";
        }
    </script>
</html>

app/templates/index.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
    <body>
		
        <h1>Flask-SocketIO-Chat</h1>
		
		<br>
		
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br><br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br><br>
			{{ form.key.label }}: {{ form.key() }} {% for error in form.key.errors %}{{ error }}{% endfor %}<br><br>
            {{ form.submit() }}
        </form>
		
		<br>
		
		<a href="#" onclick="initiate();">Initiate session</a>
        <script type="text/javascript" charset="utf-8">
            function initiate() {
            	window.location.href = "{{ url_for('main.initiateSession') }}";
            }
        </script>
			
		<br><br>
			
		<a href="#" onclick="request();">Request Room Key</a>
        <script type="text/javascript" charset="utf-8">
            function request() {
				window.location.href = "{{ url_for('main.requestKey') }}";
            }
        </script>
			
    </body>
</html>

app/templates/initiateSession.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
    <body>
        <h1>--initiate session--</h1>

    </body>
</html>

app/templates/insideChatRoom.html
<html>
    <head>
        <title>Flask-SocketIO-Chat: {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/hmac-sha256.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/enc-base64.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9/mode-cfb.min.js"></script>
		<script type="text/javascript" charset="utf-8">
            var socket;
			var sessionkey = 'f4bfdeff0cb4982d04c0da2ee79e446e';

            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });

				//new members & left members
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });

				//receiving messages
                socket.on('message', function(data) {
					var roomkey = "{{ key }}";
					var data = data.msg;

					//first iteration of decryption
					var decrypted = runPyScript( sessionkey, '0000000000000000', data)
					decrypted = decrypted.substring( 0, decrypted.indexOf("=") + 2); //remove padding
					var roomname = decrypted.substring( 0, decrypted.indexOf("|"));
					var temp = decrypted.substring( decrypted.indexOf("|") + 3);

					//second iteration of decryption
					var plaintext = decrypt(temp, roomkey);
					var username = plaintext.substring(0, plaintext.indexOf("|"));
					temp = plaintext.substring(plaintext.indexOf("|") + 3);
					var message = temp.substring(0, temp.indexOf("|")); // :))
					var mac = temp.substring(temp.indexOf("|") + 3);

					//MAC calculation
					var hash = CryptoJS.HmacSHA256( message, 'bil548'); //bil548 = secret
					var mac2 = CryptoJS.enc.Base64.stringify( hash);

					if( mac != mac2)
						$('#chat').val($('#chat').val() + 'Attention: MACs do not match for following message!\n');

					$('#chat').val($('#chat').val() + username + ': ' + message + '\n');
					$('#chat').scrollTop($('#chat')[0].scrollHeight);
                });

				//sending messages
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
						var roomname = "{{ room }}";
						var username = "{{ username }}";
						var roomkey = "{{ key }}";

						//MAC calculation
						var hash = CryptoJS.HmacSHA256( text, 'bil548'); //bil548 = secret
						var hashInBase64 = CryptoJS.enc.Base64.stringify( hash);

						//if( text == "") //parsing purposes --> causes MAC inequality
						//	text = " ";
						var temp = username + "|||" + text + "|||" + hashInBase64;

						/*
						https://stackoverflow.com/questions/59488728/aes-encrypt-in-cryptojs-decrypt-in-pycrypto
						*/
						//first iteration
						var salt = "1234salt";
						var iterations = 128;
						var bytes = CryptoJS.PBKDF2(roomkey, salt, { keySize: 48, iterations: iterations });
						var iv = CryptoJS.enc.Hex.parse(bytes.toString().slice(0, 32));
						var key = CryptoJS.enc.Hex.parse(bytes.toString().slice(32, 96));
						var ciphertext = CryptoJS.AES.encrypt(temp, key, { iv: iv });
						temp = username + '|||' + roomname + '|||' + ciphertext;


						//second iteration
						bytes = CryptoJS.PBKDF2(sessionkey, salt, { keySize: 48, iterations: iterations });
						iv = CryptoJS.enc.Hex.parse(bytes.toString().slice(0, 32));
						key = CryptoJS.enc.Hex.parse(bytes.toString().slice(32, 96));
						ciphertext = CryptoJS.AES.encrypt(temp, key, { iv: iv });

						socket.emit('text', {msg: ciphertext.toString()});
                    }
                });
            });

            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "('http://127.0.0.1:5000/')";
                });
            }

			/*
			https://stackoverflow.com/questions/32288722/call-python-function-from-js
			*/
			function runPyScript(key, iv, text){
			        var jqXHR = $.ajax({
			            type: "POST",
			            url: "/aes",
			            async: false,
			            data: { _key: key, _iv: iv, _text: text}
			        });

			        return jqXHR.responseText;
			}


			function decrypt(text, roomkey){
			        var jqXHR = $.ajax({
			            type: "POST",
			            url: "/decrypt2",
			            async: false,
			            data: { data: text, key: roomkey}
			        });

			        return jqXHR.responseText;
			}

        </script>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat: {{ room }}</h1>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
        <a href="/" onclick="leave_room();">Leave this room</a>
    </body>

</html>

app/templates/requestKey.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
    <body>
		
        <h1>**request key**</h1>
		
		<br>
		
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br><br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br><br>
            {{ form.submit() }}
        </form>
		
		<br><br><br><h1>Room name: {{room}}</h1>
        <h1>Room key: {{key}}</h1><br>
        <a href="#" onclick="leave_room();">Index page</a>
		
		<script type="text/javascript" charset="utf-8">
	        function leave_room() {
	        	// go back to the login page
	            window.location.href = "{{ url_for('main.index') }}";
	        }
	    </script>
			
    </body>
</html>